from PySide6.QtCore import Qt
from PySide6.QtWidgets import (
    QDialog, QVBoxLayout, QHBoxLayout, QPushButton,
    QTextBrowser, QSplitter, QListWidget, QListWidgetItem,
)

# ── Section registry — (anchor, sidebar label, html body) ─────────────────────
_SECTIONS = [
    ("overview",        "Overview"),
    ("step1",           "1 · Load Data"),
    ("variable_types",  "   Variable types"),
    ("sentinels",       "   Sentinel codes"),
    ("step2",           "2 · Configure & Generate"),
    ("method",          "   Choosing a method"),
    ("cart_opts",       "   CART options"),
    ("gc_opts",         "   Gaussian Copula options"),
    ("general_opts",    "   General options"),
    ("columns",         "   Column selection"),
    ("step3",           "3 · Report & Export"),
    ("ks",              "   KS test"),
    ("chi2",            "   Chi-squared test"),
    ("cat_freq",        "   Category frequencies"),
    ("corr",            "   Correlation heatmap"),
    ("privacy",         "Privacy & disclosure risk"),
]

_HTML = """
<html>
<head>
<style>
  body  { font-family: Arial, sans-serif; font-size: 12px; color: #333333;
          margin: 0 16px 24px 16px; }
  h1    { font-size: 18px; color: #5a3a8e; border-bottom: 2px solid #9063CD;
          padding-bottom: 6px; margin-top: 4px; }
  h2    { font-size: 14px; color: #5a3a8e; border-left: 4px solid #9063CD;
          padding-left: 8px; margin-top: 20px; margin-bottom: 6px; }
  h3    { font-size: 12px; color: #7a4fb5; margin-top: 12px; margin-bottom: 4px; }
  p     { margin: 5px 0; line-height: 1.6; }
  ul    { margin: 4px 0 8px 0; padding-left: 20px; }
  li    { margin: 3px 0; line-height: 1.6; }
  code  { background: #ede8f8; color: #5a3a8e; padding: 1px 4px;
          border-radius: 3px; font-family: Consolas, monospace; font-size: 11px; }
  .box  { border-radius: 4px; padding: 8px 12px; margin: 8px 0; }
  .info { background: #ede8f8; border-left: 4px solid #9063CD; }
  .tip  { background: #e8f5e9; border-left: 4px solid #61a229; }
  .warn { background: #fff8e1; border-left: 4px solid #e65100; }
  table { border-collapse: collapse; width: 100%; margin: 8px 0; }
  th    { background: #5a3a8e; color: white; padding: 5px 8px;
          text-align: left; font-size: 11px; }
  td    { padding: 5px 8px; border: 1px solid #d0c5e8;
          font-size: 11px; vertical-align: top; }
  tr:nth-child(even) td { background: #ede8f8; }
</style>
</head>
<body>

<!-- ═══════════════════════════════════════════════════════════ OVERVIEW -->
<a name="overview"></a>
<h1>SLS Synthetic Data Generator — User Guide</h1>
<p>
  This tool generates <b>synthetic datasets</b> from a real CSV file.
  A synthetic dataset has the same columns as the original and preserves
  its statistical properties (distributions, correlations, category
  frequencies) but contains no real records — every row is artificially
  generated by a statistical model.
</p>
<p>
  Synthesis is powered by
  <code>python-synthpop</code>, a Python port of the
  R <code>synthpop</code> package widely used in statistical disclosure
  control research.
</p>
<div class="box warn">
  <b>Important:</b> Synthetic data is not a formal privacy guarantee.
  It reduces disclosure risk by removing real records, but residual
  risk depends on the data and method used. See
  <i>Privacy &amp; Disclosure Risk</i> below.
</div>
<p>The workflow has three steps:</p>
<ul>
  <li><b>Step 1 — Load Data:</b> Open a CSV and classify columns.</li>
  <li><b>Step 2 — Configure &amp; Generate:</b> Choose a synthesis method, set options, and run.</li>
  <li><b>Step 3 — Report &amp; Export:</b> Review quality metrics and save your outputs.</li>
</ul>

<!-- ═══════════════════════════════════════════════════════════ STEP 1 -->
<a name="step1"></a>
<h2>Step 1 · Load Data</h2>
<p>
  Click <b>Open a CSV file to get started</b> and select any
  comma-separated values file. The tool reads the file and automatically
  detects column types and potential sentinel codes.
</p>

<a name="variable_types"></a>
<h3>Variable types</h3>
<p>
  Every column must be classified as one of three types before synthesis:
</p>
<table>
  <tr><th>Type</th><th>When to use</th><th>How it is synthesised</th></tr>
  <tr>
    <td><code>categorical</code></td>
    <td>Columns whose values represent categories or groups — e.g. sex,
        region, health condition, education level.</td>
    <td>Frequencies of each category are modelled; synthetic rows are
        drawn from those frequencies.</td>
  </tr>
  <tr>
    <td><code>numeric</code></td>
    <td>Columns containing continuous or integer measurements — e.g. age,
        income, year, test score.</td>
    <td>The distribution and relationships with other variables are
        modelled and resampled.</td>
  </tr>
  <tr>
    <td><code>ignore</code></td>
    <td>Columns to exclude from synthesis entirely — e.g. unique IDs,
        free-text fields, dates not needed in output.</td>
    <td>Not included in the synthetic dataset.</td>
  </tr>
</table>
<div class="box tip">
  <b>Auto-detection:</b> The tool classifies columns automatically using
  cardinality (number of unique values). Columns with ≤ 20 unique values
  (or ≤ 50 for text columns) are marked <code>categorical</code>;
  higher-cardinality columns are marked <code>numeric</code>.
  Always review the suggestions — a year column with 10 unique values
  might be better treated as numeric.
</div>

<a name="sentinels"></a>
<h3>Sentinel codes</h3>
<p>
  Many survey datasets encode missing or special responses as negative
  numeric codes — for example <code>-99</code> (not answered),
  <code>-8</code> (don't know), <code>-9</code> (refused).
  If left in the data, synthesis treats them as real values and may
  generate impossible combinations.
</p>
<p>
  The tool automatically scans numeric columns for known sentinel patterns
  (values in the set <code>-1, -2, -6, -7, -8, -9, -66, -77, -88, -99,
  -999</code>, etc.) that appear in fewer than 5% of non-null values.
  Pre-checked codes are likely sentinels; un-check any that are
  legitimate values.
</p>
<p>
  Checked codes are replaced with <code>NaN</code> before synthesis.
</p>

<!-- ═══════════════════════════════════════════════════════════ STEP 2 -->
<a name="step2"></a>
<h2>Step 2 · Configure &amp; Generate</h2>

<a name="method"></a>
<h3>Choosing a synthesis method</h3>
<table>
  <tr><th></th><th>CART</th><th>Gaussian Copula</th></tr>
  <tr>
    <td><b>Approach</b></td>
    <td>Synthesises each column sequentially using a Classification and
        Regression Tree fitted on all previously synthesised
        columns.</td>
    <td>Fits a multivariate normal copula to model dependencies among
        numeric columns, then applies per-column marginal
        distributions.</td>
  </tr>
  <tr>
    <td><b>Strengths</b></td>
    <td>Handles mixed data (numeric and categorical) naturally. Preserves
        complex non-linear relationships and interactions between
        variables. Generally the better default.</td>
    <td>Faster on large datasets. Theoretically elegant for
        predominantly numeric data.</td>
  </tr>
  <tr>
    <td><b>Weaknesses</b></td>
    <td>Slower on very wide datasets (many columns). Can struggle with
        very high-cardinality categorical variables.</td>
    <td>Assumes relationships are well-described by a Gaussian
        copula structure. May not capture non-linear dependencies
        or mixed data well.</td>
  </tr>
  <tr>
    <td><b>Recommendation</b></td>
    <td colspan="2">Start with <b>CART</b> unless you have a specific
        reason to use Gaussian Copula.</td>
  </tr>
</table>

<a name="cart_opts"></a>
<h3>CART options</h3>
<table>
  <tr><th>Option</th><th>Default</th><th>Explanation</th></tr>
  <tr>
    <td><b>Smoothing</b></td>
    <td>Off</td>
    <td>Adds small random noise drawn from within each leaf node of the
        decision tree, making the synthetic distribution less discretely
        "blocky". Recommended for continuous numeric variables.</td>
  </tr>
  <tr>
    <td><b>Proper synthesis</b></td>
    <td>Off</td>
    <td>Re-fits the CART model on a bootstrap sample of the data, adding
        model uncertainty to the synthetic values. Produces more
        statistically "proper" inference-safe synthetic data at the
        cost of slightly lower fidelity.</td>
  </tr>
  <tr>
    <td><b>Minibucket</b></td>
    <td>5</td>
    <td>Minimum number of observations required in a leaf node before
        the tree stops splitting. Higher values produce simpler,
        smoother models; lower values capture finer patterns but risk
        over-fitting or producing near-real records. Keep at 5 or above
        for privacy.</td>
  </tr>
  <tr>
    <td><b>Random state</b></td>
    <td>42</td>
    <td>Seed for the random number generator. Using the same seed with
        the same data and settings produces identical synthetic data,
        enabling reproducibility. Change it to get a different
        synthetic sample.</td>
  </tr>
</table>

<a name="gc_opts"></a>
<h3>Gaussian Copula options</h3>
<table>
  <tr><th>Option</th><th>Default</th><th>Explanation</th></tr>
  <tr>
    <td><b>Enforce min/max values</b></td>
    <td>On</td>
    <td>Clips synthetic values to the observed minimum and maximum of
        each column. Prevents the copula from generating impossible
        values (e.g. negative ages). Recommended.</td>
  </tr>
  <tr>
    <td><b>Enforce rounding</b></td>
    <td>On</td>
    <td>Rounds synthetic values to match the decimal precision of the
        original column. For example, if all original values are whole
        numbers, synthetic values will also be whole numbers.</td>
  </tr>
  <tr>
    <td><b>Default distribution</b></td>
    <td>beta</td>
    <td>The marginal distribution fitted to each numeric column before
        the copula transformation is applied:
        <ul>
          <li><code>norm</code> — standard normal distribution</li>
          <li><code>beta</code> — bounded distribution, rescaled to 0–1</li>
          <li><code>truncnorm</code> — normal distribution hard-clipped
              at the observed min/max</li>
          <li><code>uniform</code> — flat distribution between min and max</li>
        </ul>
        If unsure, try <code>beta</code> first.
    </td>
  </tr>
</table>

<a name="general_opts"></a>
<h3>General options</h3>
<table>
  <tr><th>Option</th><th>Explanation</th></tr>
  <tr>
    <td><b>Output rows</b></td>
    <td>Number of rows in the synthetic dataset. Defaults to the number
        of rows in the original data. You can generate more or fewer rows
        than the original — the model is trained once and sampled as many
        times as needed.</td>
  </tr>
  <tr>
    <td><b>Skip missing-data imputation</b></td>
    <td>When checked (recommended), missing values (<code>NaN</code>)
        are left as-is and handled natively by synthpop during model
        fitting. When unchecked, an imputation step fills in missing
        values before fitting, which can sometimes improve fidelity but
        adds time and may introduce artefacts.</td>
  </tr>
  <tr>
    <td><b>Max training rows</b></td>
    <td>Maximum rows used to <i>train</i> the synthesis model. If the
        dataset is larger, a random subsample of this size is drawn for
        fitting. The full dataset is not required for training — the
        model only needs a representative sample. Reducing this value
        dramatically speeds up synthesis on large datasets with
        minimal quality loss. The output can still have as many rows
        as requested in <i>Output rows</i>.</td>
  </tr>
</table>
<div class="box warn">
  Training on more than 50,000 rows may take many minutes. Consider
  reducing <b>Max training rows</b> to 20,000–50,000 for exploratory runs.
</div>

<a name="columns"></a>
<h3>Column selection</h3>
<p>
  The checklist shows all columns classified as <code>categorical</code>
  or <code>numeric</code> on the Load Data tab. Uncheck any columns you
  want to exclude from synthesis even though they are not marked
  <code>ignore</code>. Use <b>Select All / Deselect All</b> for bulk
  changes.
</p>
<div class="box info">
  Excluding highly identifying columns (e.g. a postcode sector, a rare
  combination) from synthesis is one way to reduce disclosure risk in
  the output.
</div>

<p>
  Click <b>Estimate synthesis time</b> to run a brief benchmark on a
  small sample before committing to a full synthesis run.
  The estimate is approximate — actual time depends on the data structure.
</p>

<!-- ═══════════════════════════════════════════════════════════ STEP 3 -->
<a name="step3"></a>
<h2>Step 3 · Report &amp; Export</h2>
<p>
  After synthesis completes, a quality report is generated automatically.
  It compares the synthetic dataset against the original across several
  dimensions. A passing report does not guarantee fitness for all purposes
  — it shows that the gross statistical properties are preserved.
</p>

<a name="ks"></a>
<h3>Kolmogorov–Smirnov (KS) test — numeric variables</h3>
<p>
  The two-sample KS test asks: <i>could the synthetic values and the real
  values have been drawn from the same continuous distribution?</i>
</p>
<ul>
  <li><b>KS statistic:</b> Maximum absolute difference between the two
      empirical CDFs. 0 = identical distributions, 1 = completely
      different.</li>
  <li><b>p-value ≥ 0.05 (✓):</b> No statistically significant difference
      detected — the synthetic distribution is consistent with the real
      one.</li>
  <li><b>p-value &lt; 0.05 (✗):</b> A significant difference exists.
      For large datasets this can trigger easily even for minor
      differences that are practically irrelevant. Use the numeric
      summary table alongside to judge severity.</li>
</ul>

<a name="chi2"></a>
<h3>Chi-squared test — categorical variables</h3>
<p>
  Tests whether the observed category frequencies in the synthetic data
  are consistent with those in the real data.
</p>
<ul>
  <li><b>p-value ≥ 0.05 (✓):</b> Frequency distributions are consistent.</li>
  <li><b>p-value &lt; 0.05 (✗):</b> Frequencies differ significantly.
      Check the category frequency table below to see which
      categories are misrepresented.</li>
</ul>

<a name="cat_freq"></a>
<h3>Categorical frequency comparison</h3>
<p>
  Shows the percentage breakdown of each category in the real and
  synthetic data side by side. Differences larger than 5% are
  highlighted in orange. Aim for close alignment, especially on
  categories that will be used in downstream analysis.
</p>

<a name="corr"></a>
<h3>Correlation heatmap — numeric variables</h3>
<p>
  Displays three Pearson correlation matrices side by side:
</p>
<ul>
  <li><b>Real:</b> correlation structure of the original data.</li>
  <li><b>Synthetic:</b> correlation structure of the synthetic data.</li>
  <li><b>Absolute difference:</b> cell-by-cell absolute difference
      between the two matrices (white/red scale).</li>
</ul>
<p>
  The <b>mean absolute correlation difference</b> (upper triangle) is a
  single summary number: lower is better. Values below 0.05 indicate
  that the correlation structure is very well preserved; values above
  0.15 suggest meaningful divergence in relationships between variables.
</p>

<!-- ═══════════════════════════════════════════════════════════ PRIVACY -->
<a name="privacy"></a>
<h2>Privacy &amp; Disclosure Risk</h2>
<div class="box warn">
  <b>Synthetic data is not a formal privacy guarantee.</b>
  The tool produces statistically similar data, not verified
  disclosure-controlled data. Do not release synthetic data derived from
  SLS records without consulting the SLS-DSU.
</div>
<p>
  Synthetic data reduces disclosure risk in several ways:
</p>
<ul>
  <li>No row in the synthetic dataset corresponds to a real individual.</li>
  <li>The model generalises across many records, making it harder to
      recover any specific record.</li>
  <li>Rare combinations are smoothed out by the statistical model
      (especially with higher <code>minibucket</code> values in CART).</li>
</ul>
<p>
  However, residual risks remain:
</p>
<ul>
  <li><b>Attribute inference:</b> If the model preserves strong
      relationships between variables, an attacker with partial knowledge
      may infer missing attributes.</li>
  <li><b>Membership inference:</b> With enough background knowledge,
      an attacker may determine whether a given individual's record was
      in the training data.</li>
  <li><b>Model inversion:</b> In extreme cases, training on very small
      datasets can cause the model to memorise individual records.</li>
</ul>
<p>
  Practical mitigations within this tool:
</p>
<ul>
  <li>Use <b>Max training rows</b> to subsample large datasets —
      smaller training sets reduce memorisation risk.</li>
  <li>Use higher <b>Minibucket</b> values (10–25) to coarsen the CART
      model and reduce near-exact record reproduction.</li>
  <li>Exclude highly identifying variables from synthesis using the
      column selection checklist.</li>
  <li>Mark quasi-identifiers (e.g. postcode, date of birth, rare
      conditions) as <code>ignore</code> where possible.</li>
</ul>
<p>
  The synthetic dataset must not be treated as real data or used
  to make inferences about specific individuals.
</p>

</body>
</html>
"""


class HelpDialog(QDialog):
    """Scrollable user guide with sidebar navigation."""

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setWindowTitle("SLS Synthetic Data Generator — User Guide")
        self.resize(860, 640)
        self._build_ui()

    def _build_ui(self):
        root = QVBoxLayout(self)
        root.setContentsMargins(0, 0, 0, 0)
        root.setSpacing(0)

        splitter = QSplitter(Qt.Orientation.Horizontal)

        # Sidebar
        self._sidebar = QListWidget()
        self._sidebar.setFixedWidth(200)
        self._sidebar.setStyleSheet(
            "QListWidget { border: none; border-right: 1px solid #d0c5e8;"
            "  background: #f4f1fa; font-size: 11px; }"
            "QListWidget::item { padding: 5px 10px; }"
            "QListWidget::item:selected { background: #9063CD; color: white; }"
            "QListWidget::item:hover:!selected { background: #ede8f8; }"
        )
        for anchor, label in _SECTIONS:
            item = QListWidgetItem(label)
            item.setData(Qt.ItemDataRole.UserRole, anchor)
            self._sidebar.addItem(item)
        self._sidebar.currentItemChanged.connect(self._on_nav)
        splitter.addWidget(self._sidebar)

        # Content browser
        self._browser = QTextBrowser()
        self._browser.setHtml(_HTML)
        self._browser.setOpenLinks(False)
        self._browser.setStyleSheet(
            "QTextBrowser { border: none; background: white; }"
        )
        splitter.addWidget(self._browser)
        splitter.setSizes([200, 660])

        root.addWidget(splitter, stretch=1)

        # Close button
        btn_row = QHBoxLayout()
        btn_row.setContentsMargins(12, 8, 12, 8)
        btn_row.addStretch()
        close_btn = QPushButton("Close")
        close_btn.setFixedWidth(90)
        close_btn.clicked.connect(self.accept)
        btn_row.addWidget(close_btn)
        root.addLayout(btn_row)

        self._sidebar.setCurrentRow(0)

    def _on_nav(self, current, _previous):
        if current is None:
            return
        anchor = current.data(Qt.ItemDataRole.UserRole)
        self._browser.scrollToAnchor(anchor)
